config/routes.rb
CrashServer::Application.routes.draw do
  root :to           => 'apps#index'
  post 'exception'   => 'apps#exception'
  post 'capistrano'  => 'apps#capistrano' 
  
  resources :apps do
    match 'generate_key' => 'apps#generate_key', :as => 'generate_key'
    
    resources :crashes do
      match 'close' => 'crashes#close', :as => 'close'
    end
  end
end

app/models/app.rb
class App < ActiveRecord::Base
  include Payload
  
  has_many :crashes, :dependent => :destroy
  has_many :deployments, :dependent => :destroy
  
  validates_presence_of   :name, :api_key
  validates_length_of     :name, :within => 2..64
  validates_uniqueness_of :name
  validates_uniqueness_of :api_key
  
  before_validation :assign_api_key, :on => :create
  
  def register_crash(payload)
    uuid = payload_uuid(payload)
    crash = self.crashes.find_by_uuid(uuid)
    unless crash.nil?
      crash.just_happened
    else    
      crash = self.crashes.new
      crash.assign_payload(payload)
      crash.save
    end
    crash
  end
  
  def reset_api_key!
    self.update_attribute(:api_key, generate_api_key)
  end
  
  private
  
  def assign_api_key
    self.api_key = generate_api_key if new_record?
  end
  
  def generate_api_key
    UUIDTools::UUID.random_create.to_s.gsub(/-/,'')
  end
end

app/models/crash.rb
require 'yaml'

class Crash < ActiveRecord::Base
  include Payload
  
  belongs_to :app
  
  validates_presence_of :app_id, :uuid
  
  default_scope :order => 'last_occurred_at DESC'
  
  scope :active, :conditions => ['status = ?', 'open']
  scope :closed, :conditions => ['status = ?', 'closed']
  
  def to_s
    "#{self.class_name}: #{self.message}"
  end
  
  def open?
    self.status == 'open'
  end
  
  def close
    self.update_attribute(:status, 'closed')
  end
  
  def assign_payload(p)
    ts = p['exception']['timestamp']
    ts = Time.parse(ts) unless ts.kind_of?(Time)
    
    self.update_attributes(   
      :uuid             => payload_uuid(p),
      :class_name       => p['exception']['class_name'],
      :message          => p['exception']['message'],
      :backtrace        => p['exception']['backtrace'].join("\r\n"),
      :environment      => YAML.dump(p['environment']),
      :framework        => p['framework'],
      :created_at       => ts,
      :last_occurred_at => ts
    )
  end
  
  def just_happened
    self.update_attributes(
      :status           => 'open',
      :last_occurred_at => Time.now,
      :occurrences      => self.occurrences + 1
    )
  end
end

app/models/deployment.rb
class Deployment < ActiveRecord::Base
  belongs_to :app
  
  default_scope :order => 'created_at DESC'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  protected
  
  def find_api_by_api_key
    @app = App.find_by_api_key(params[:api_key])
    if @app.nil?
      return render :json => {:error => "Invalid API key."}
    end
  end
  
  def find_app
    @app = App.find_by_id(params[:app_id] || params[:id])
    if @app.nil?
      flash[:error] = "Unable to find app."
      return redirect_to apps_path
    end
  end
  
  def find_crash
    @crash = @app.crashes.find_by_id(params[:crash_id] || params[:id])
    if @crash.nil?
      flash[:error] = "Unable to find the record."
      return redirect_to app_path(@app)
    end
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_filter :find_app, :except => [:index, :new, :create, :exception, :capistrano]
  before_filter :find_api_by_api_key, :only => [:exception, :capistrano]
  
  def index
    @apps = App.all
  end
  
  def show
    @active_issues = @app.crashes.active
    @closed_issues = @app.crashes.closed
    @deployments   = @app.deployments
  end
  
  def new
    @app = App.new
  end
  
  def create
    @app = App.new(params[:app])
    if @app.save
      flash[:success] = "New app has been created."
      redirect_to app_path(@app)
    else
      flash[:error] = "Unable to create app."
      render :new
    end
  end
  
  def update
    if @app.update_attributes(params[:app])
      flash[:success] = "Application has been updated."
      return redirect_to app_path(@app)
    else
      flash[:error] = "Unable to update information."
      render :edit
    end
  end
  
  def destroy
    @app.destroy
    if @app.destroyed?
      flash[:success] = "App has been deleted."
    else
      flash[:error] = "App could not be deleted."
    end
    redirect_to apps_path
  end
  
  # Regenerate API key
  def generate_key
    old = @app.api_key
    @app.reset_api_key!
    if @app.api_key != old
      flash[:success] = "API key has been changed."
    else
      flash[:error] = "Unable to reset API key."
    end
    return redirect_to app_path(@app)
  end
  
  # Primary API endpoint for exceptions
  # POST /exception
  def exception
    data = params['crash']
    @app.register_crash(data)
    render :json => {:success => true}
  end
  
  # Primary API endpoint for capistrano deployments
  # POST /capistrano
  def capistrano
    p = MultiJson.decode(params[:payload])
    capistrano = p['capistrano']
    
    @app.deployments.create(
      :capistrano_version => capistrano['version'],
      :payload_version    => p['payload_version'],
      :deployer_user      => capistrano['deployer']['user'],
      :deployer_hostname  => capistrano['deployer']['hostname'],
      :source_branch      => capistrano['source']['branch'],
      :source_revision    => capistrano['source']['revision'],
      :source_repository  => capistrano['source']['repository'],
      :action             => capistrano['action'],
      :message            => capistrano['message'],
      :created_at         => capistrano['timestamp']
    )
    
    render :json => {:success => true}
  end
end

app/controllers/crashes_controller.rb
class CrashesController < ApplicationController
  before_filter :find_app
  before_filter :find_crash, :only => [:show, :close]
  
  def show
    @env = YAML.load(@crash.environment)
  end
  
  def close
    if @crash.close
      flash[:success] = "Issue has been closed."
      redirect_to app_path(@app)
    else
      flash[:error] = "Unable to close the issue."
      redirect_to app_crash_path(@app, @crash)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    unless flash.empty?
      msg = []
      flash.each_pair do |k,v|
        msg << "<div class='flash-message flash-#{k.to_s}'>#{v.to_s}</div>"
      end
      flash.discard
      msg.join("\n").html_safe
    else
      ''
    end
  end
  
  def render_crashes_table(records)
    render :partial => 'shared/crashes_table', :locals => {:crashes => records}
  end
  
  def render_deployments_table(records)
    render :partial => 'shared/deployments_table', :locals => {:deployments => records}
  end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/crashes_helper.rb
module CrashesHelper
  include UserAgents
  
  def render_backtrace(content)
    content.split("\r\n").map { |l| "<div class='line'>#{l}</div>" }.join.html_safe
  end
end

app/views/apps/_form.html.erb
<%= simple_form_for @app do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/apps/edit.html.erb
<h1>Edit App</h1>
<%= render :partial => 'form' %>

app/views/apps/index.html.erb
<div class="exception-title">
  <h1>Applications</h1>
</div>
<div class="block">
  <%= link_to 'New Application', new_app_path, :class => 'button' %>
</div>

<% @apps.each do |app| %>
  <div class="block">
    <h3><%= app.name %></h3>
    <ul>
      <li><strong>Open issues:</strong> <%= app.crashes.active.count %></li>
      <li><strong>Closed issues:</strong> <%= app.crashes.closed.count %>
    </ul>
    <%= link_to 'view', app_path(app), :class => 'button' %>
  </div>
<% end %>

app/views/apps/new.html.erb
<h1>New application</h1>
<%= render :partial => 'form' %>

app/views/apps/show.html.erb
<div class="exception-title"><h1><%= @app.name %></h1></div>
<div class="block">
  <ul>
    <li><strong>Created:</strong> <%= @app.created_at.to_s(:short) %></li>
    <li><strong>API Key:</strong> <%= @app.api_key %></li>
    <li><strong>Status:</strong> <%= @app.enabled ? 'Active' : 'Disabled' %></li>
  </ul>
</div>
<div class="block">
  <%= link_to 'Edit', edit_app_path(@app), :class => 'button' %>
  <%= link_to 'Reset API key', app_generate_key_path(@app), :confirm => "Are you sure?", :class => 'button' %>
  <%= link_to 'Delete', app_path(@app), :method => :delete, :confirm => "Are you sure?", :class => 'button' %>
</div>
<div class="block">
  <h3>Active Issues</h3>
  <%= render_crashes_table(@active_issues) %>
</div>
<div class="block">
  <h3>Closed Issues</h3>
  <%= render_crashes_table(@closed_issues) %>
</div>
<div class="block">
  <h3>Capistrano Deployments</h3>
  <%= render_deployments_table(@deployments) %>
</div>

app/views/crashes/show.html.erb
<div class="exception-title">
  <h1>
    <span class="<%= @crash.status %>"><%= @crash.status %></span>
    <%= @crash.to_s %>
  </h1>
</div>
<% if @crash.open? %>
  <div class="block">
    <%= link_to 'Close this issue', app_crash_close_path(@app, @crash), :class => 'button' %>
  </div>
<% end %>
<div class="block">
  <h3>Overview</h3>
  <ul>
    <li>First occurred on: <%= @crash.created_at.strftime("%B %d %Y, %H:%I:%S") %></li>
    <li>Last occurred on: <%= @crash.last_occurred_at.strftime("%B %d %Y, %H:%I:%S") %></li>
    <li>Total occurrences: <%= @crash.occurrences %></li>
  </ul>
</div>
<div class="block request">
  <div class="request-string">
    <%= @env['REQUEST_METHOD'] %> <%= @env['SERVER_PROTOCOL'] =~ /https/ ? 'https://' : 'http://' %><%= @env['HTTP_HOST'] %><%= @env['REQUEST_PATH'] %>
  </div>
  <% if @crash.framework == 'rails' %>
    <div class="rails-info">
      <span>Controller: </span><%= @env['action_dispatch.request.path_parameters']['controller'] %>#<%= @env['action_dispatch.request.path_parameters']['action'] %>
    </div>
  <% end %>
</div>
<div class="block">
  <h3>Client</h3>
  <ul>
    <li><strong>Agent:</strong> <%= @env['HTTP_USER_AGENT'] %></li>
    <li><strong>IP:</strong> <%= @env['REMOTE_ADDR'] %></li>
  </ul>
</div>
<div class="block environment">
  <h3>Environment</h3>
  <table class="env">
    <% keys = @env.keys.sort %>
    <% keys.each do |k| v = @env[k] %>
      <tr>
        <td class="key"><%= k %></td>
        <td class="value"><p><%= v %></p></td>
      </tr>
    <% end %>
  </table>
</div>
<div class="block">
  <h3>Backtrace</h3>
  <pre class="backtrace"><%= render_backtrace(@crash.backtrace) %></pre>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
    <title>CrashServer</title>    
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <%= stylesheet_link_tag 'master' %>
    <%= javascript_include_tag 'jquery', 'rails', 'application' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="wrapper">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_crashes_table.html.erb
<table class="issues-list" cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <th>Status</th>
      <th>Exception</th>
      <th>First time</th>
      <th>Last time</th>
      <th>Count</th>
    </tr>
  </thead>
  <tbody>
    <% unless crashes.empty? %>
      <% crashes.each do |c| %>
        <tr>
          <td class="field-status"><span class="<%= c.status %>"><%= c.status %></span></td>
          <td class="field-name"><%= link_to c.to_s, app_crash_path(@app, c) %></td>
          <td class="field-time"><%= c.created_at.to_s(:long) %></td>
          <td class="field-time"><%= c.last_occurred_at.to_s(:long) %></td>
          <td class="field-occurrences"><%= c.occurrences %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="5"><p class="no-records">No records found.</p></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_deployments_table.html.erb
<table class="issues-list" cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <th>Action</th>
      <th>Branch</th>
      <th>Revision</th>
      <th>Message</th>
      <th>Deployer</th>
      <th>Timestamp</th>
    </tr>
  </thead>
  <tbody>
    <% unless deployments.empty? %>
      <% deployments.each do |d| %>
        <tr>
          <td class="field-status"><span class="<%= d.action %>"><%= d.action %></span></td>
          <td><%= d.source_branch %></td>
          <td><%= d.source_revision[0..7] %></td>
          <td><%= d.message %></td>
          <td class="field-name"><%= d.deployer_user %> @ <%= d.deployer_hostname %></td>
          <td class="field-time"><%= d.created_at.to_s(:long) %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="5"><p class="no-records">No records found.</p></td>
      </tr>
    <% end %>
  </tbody>
</table>